spring.application.name=spring-mvc-day-01-introduction
server.web.error.include-message=always
server.web.error.include-binding-errors=always
server.web.error.include-stacktrace=always
spring.web.error.include-exception=true